version: "3"

services:
  py:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: project_slug_local
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.env
    command: pwd
