version: "3"

services:
  py:
    build:
      args:
        USER_ID: 1000
        GROUP_ID: 1000
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: project_slug_local
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.env
    working_dir: /app
    # entrypoint: "./compose/local/startup.sh"
    command: python3 ./project_slug/project_slug.py
